# Use a lightweight Python base image
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy MLflow server dependencies
COPY requirements-mlflow.txt .

# Install the MLflow server dependencies
RUN pip install --no-cache-dir -r requirements-mlflow.txt

# Run the MLflow tracking server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
