# GitHub Actions workflow for building the Docker image
name: CD

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest
        # Allow GitHub Actions to publish Docker images to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      # Download the project files from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t olist-api:1.0 .
